# Generated by Django 2.2.3 on 2019-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190713_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='article_type',
            field=models.CharField(choices=[('1', 'Programming'), ('2', 'UX/UI'), ('3', 'Electronics'), ('4', 'Other')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
