# Generated by Django 2.2.3 on 2019-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190716_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='article_type',
            field=models.CharField(choices=[('Programming', 'Programming'), ('UX/UI', 'UX/UI'), ('Electronics', 'Electronics'), ('Other', 'Other')], default='1', max_length=20),
        ),
    ]
