# Generated by Django 2.2.3 on 2019-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190804_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
        # migrations.AlterField(
        #     model_name='blogpost',
        #     name='title',
        #     field=models.TextField(unique=True),
        # ),
    ]
