# Generated by Django 2.2.3 on 2019-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_url',
            field=models.CharField(default='#', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
